export const Products = [
  {
    id: "1",
    name: "airpoods wirless",
    image: "/images/airpods.jpg",
    description: "dasdasdasdasdsada sdasd asdas dasdas asd asdas ds",
    brand: "apple",
    category: "electronics",
    price: 90,
    countinstocks: 3,
    rating: 4,
    numReviews: 4,
  },

  {
    id: "2",
    name: "phone ",
    image: "/images/phone.jpg",
    description: "dasdasdasdasdsada sdasd asdas dasdas asd asdas ds",
    brand: "apple",
    category: "electronics",
    price: 90,
    countinstocks: 0,
    rating: 4,
    numReviews: 4,
  },
  {
    id: "3",
    name: "alexa wirless",
    image: "/images/alexa.jpg",
    description: "dasdasdasdasdsada sdasd asdas dasdas asd asdas ds",
    brand: "apple",
    category: "electronics",
    price: 90,
    countinstocks: 3,
    rating: 4,
    numReviews: 4,
  },
  {
    id: "4",
    name: "camera ",
    image: "/images/mouse.jpg",
    description: "dasdasdasdasdsada sdasd asdas dasdas asd asdas ds",
    brand: "apple",
    category: "electronics",
    price: 90,
    countinstocks: 0,
    rating: 5,
    numReviews: 4,
  },
  {
    id: "5",
    name: "mouse wirless",
    image: "/images/playstation.jpg",
    description: "dasdasdasdasdsada sdasd asdas dasdas asd asdas ds",
    brand: "apple",
    category: "electronics",
    price: 90,
    countinstocks: 3,
    rating: 4.5,
    numReviews: 3,
  },
  {
    id: "6",
    name: "playstation wirless",
    image: "/images/camera.jpg",
    description: "dasdasdasdasdsada sdasd asdas dasdas asd asdas ds",
    brand: "apple",
    category: "electronics",
    price: 90,
    countinstocks: 3,
    rating: 3,
    numReviews: 1,
  },
];
